//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ventura.musicexplorer.ui.widget;

import android.app.Activity;
import android.content.Context;
import android.util.AttributeSet;
import android.widget.TextView;
import com.ventura.musicexplorer.R.id;
import com.ventura.musicexplorer.R.layout;


/**
 * We use @SuppressWarning here because our java code
 * generator doesn't know that there is no need
 * to import OnXXXListeners from View as we already
 * are in a View.
 * 
 */
@SuppressWarnings("unused")
public final class KeyValuePanel_
    extends KeyValuePanel
{

    private Context context_;
    private boolean mAlreadyInflated_ = false;

    public KeyValuePanel_(Context context, AttributeSet attrs) {
        super(context, attrs);
        init_();
    }

    public KeyValuePanel_(Context context, String key, String value) {
        super(context, key, value);
        init_();
    }

    public KeyValuePanel_(Context context, String key, String value, String keyDelimiter) {
        super(context, key, value, keyDelimiter);
        init_();
    }

    private void init_() {
        context_ = getContext();
        if (context_ instanceof Activity) {
            Activity activity = ((Activity) context_);
        }
    }

    private void afterSetContentView_() {
        key = ((TextView) findViewById(id.key));
        value = ((TextView) findViewById(id.value));
        setViewData();
    }

    /**
     * The mAlreadyInflated_ hack is needed because of an Android bug
     * which leads to infinite calls of onFinishInflate()
     * when inflating a layout with a parent and using
     * the <merge /> tag.
     * 
     */
    @Override
    public void onFinishInflate() {
        if (!mAlreadyInflated_) {
            mAlreadyInflated_ = true;
            inflate(getContext(), layout.key_value_panel, this);
            afterSetContentView_();
        }
        super.onFinishInflate();
    }

    public static KeyValuePanel build(Context context, AttributeSet attrs) {
        KeyValuePanel_ instance = new KeyValuePanel_(context, attrs);
        instance.onFinishInflate();
        return instance;
    }

    public static KeyValuePanel build(Context context, String key, String value) {
        KeyValuePanel_ instance = new KeyValuePanel_(context, key, value);
        instance.onFinishInflate();
        return instance;
    }

    public static KeyValuePanel build(Context context, String key, String value, String keyDelimiter) {
        KeyValuePanel_ instance = new KeyValuePanel_(context, key, value, keyDelimiter);
        instance.onFinishInflate();
        return instance;
    }

}
