//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ventura.umusic.ui.release;

import java.util.List;
import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.AdapterView;
import android.widget.AdapterView.OnItemClickListener;
import android.widget.ListView;
import android.widget.ProgressBar;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.ventura.umusic.R.layout;
import com.ventura.umusic.discogs.entity.ArtistRelease;

public final class ReleasesListActivity_
    extends ReleasesListActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.default_list);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        loadingProgressBar = ((ProgressBar) findViewById(com.ventura.umusic.R.id.loadingListProgressBar));
        list = ((ListView) findViewById(android.R.id.list));
        {
            AdapterView<?> view = ((AdapterView<?> ) findViewById(android.R.id.list));
            if (view!= null) {
                view.setOnItemClickListener(new OnItemClickListener() {


                    @Override
                    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                        onArtistReleaseClicked(((ArtistRelease) parent.getAdapter().getItem(position)));
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static ReleasesListActivity_.IntentBuilder_ intent(Context context) {
        return new ReleasesListActivity_.IntentBuilder_(context);
    }

    @Override
    public void updateListView(final List<ArtistRelease> data) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ReleasesListActivity_.super.updateListView(data);
                } catch (RuntimeException e) {
                    Log.e("ReleasesListActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void getArtistReleases(final int artistId) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ReleasesListActivity_.super.getArtistReleases(artistId);
                } catch (RuntimeException e) {
                    Log.e("ReleasesListActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ReleasesListActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ReleasesListActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
