//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ventura.umusic.ui.artist;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.ViewGroup.LayoutParams;
import android.widget.ListView;
import android.widget.ProgressBar;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.ventura.umusic.R.layout;
import com.ventura.umusic.discogs.entity.SearchResult;
import com.ventura.umusic.discogs.entity.enumerator.QueryType;

public final class ArtistsListActivity_
    extends ArtistsListActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.default_list);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        list = ((ListView) findViewById(android.R.id.list));
        loadingProgressBar = ((ProgressBar) findViewById(com.ventura.umusic.R.id.loadingListProgressBar));
        afterViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static ArtistsListActivity_.IntentBuilder_ intent(Context context) {
        return new ArtistsListActivity_.IntentBuilder_(context);
    }

    @Override
    public void updateListView(final SearchResult data) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    ArtistsListActivity_.super.updateListView(data);
                } catch (RuntimeException e) {
                    Log.e("ArtistsListActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void listArtists(final QueryType queryType, final String query) {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ArtistsListActivity_.super.listArtists(queryType, query);
                } catch (RuntimeException e) {
                    Log.e("ArtistsListActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void loadMore() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    ArtistsListActivity_.super.loadMore();
                } catch (RuntimeException e) {
                    Log.e("ArtistsListActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, ArtistsListActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public ArtistsListActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
