//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ventura.musicexplorer.ui;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import com.ventura.musicexplorer.R.id;
import com.ventura.musicexplorer.R.layout;
import com.ventura.musicexplorer.ui.widget.KeyValuePanel;

public final class AboutActivity_
    extends AboutActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.about);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        appVersion = ((KeyValuePanel) findViewById(id.app_version));
        developerName = ((KeyValuePanel) findViewById(id.developer_name));
        {
            View view = findViewById(id.btn_send_email);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AboutActivity_.this.sendEmail();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btn_rate_app);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        AboutActivity_.this.openGooglePlayPage();
                    }

                }
                );
            }
        }
        updateText();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static AboutActivity_.IntentBuilder_ intent(Context context) {
        return new AboutActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, AboutActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public AboutActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
