//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ventura.musicexplorer.ui.music;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.os.Handler;
import android.util.Log;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageButton;
import android.widget.ImageView;
import android.widget.ProgressBar;
import android.widget.SeekBar;
import android.widget.TextView;
import com.googlecode.androidannotations.api.BackgroundExecutor;
import com.ventura.musicexplorer.R.id;
import com.ventura.musicexplorer.R.layout;
import com.ventura.musicexplorer.lyrdb.entities.Lyric;

public final class MusicPlayerActivity_
    extends MusicPlayerActivity
{

    private Handler handler_ = new Handler();

    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.musicplayer);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        btnPrevious = ((ImageButton) findViewById(id.btnPrevious));
        btnPlaylist = ((ImageButton) findViewById(id.btnPlaylist));
        lblSongTotalDuration = ((TextView) findViewById(id.songTotalDurationLabel));
        lblArtistName = ((TextView) findViewById(id.artist_name));
        lblSongCurrentDuration = ((TextView) findViewById(id.songCurrentDurationLabel));
        btnNext = ((ImageButton) findViewById(id.btnNext));
        btnPlay = ((ImageButton) findViewById(id.btnPlay));
        lblSongLyrics = ((TextView) findViewById(id.songLyrics));
        songThumbnail = ((ImageView) findViewById(id.songThumbnail));
        songProgressBar = ((SeekBar) findViewById(id.songProgressBar));
        btnPause = ((ImageButton) findViewById(id.btnPause));
        btnRepeat = ((ImageButton) findViewById(id.btnRepeat));
        btnShuffle = ((ImageButton) findViewById(id.btnShuffle));
        lblSongTitle = ((TextView) findViewById(id.songTitle));
        lyricsLoadingProgressBar = ((ProgressBar) findViewById(id.lyricsLoadingProgressBar));
        {
            View view = findViewById(id.btnPlaylist);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.onPlaylistButtonClick(view);
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnShuffle);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.toggleShuffle();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnPause);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.pause();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnNext);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.next();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnPlay);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.play();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnPrevious);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.prev();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnRepeat);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.toggleRepeat();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static MusicPlayerActivity_.IntentBuilder_ intent(Context context) {
        return new MusicPlayerActivity_.IntentBuilder_(context);
    }

    @Override
    public void setSongLyrics(final Lyric lyrics) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    MusicPlayerActivity_.super.setSongLyrics(lyrics);
                } catch (RuntimeException e) {
                    Log.e("MusicPlayerActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void updateProgressBarViews(final String currentDuration, final String totalDuration, final int progress) {
        handler_.post(new Runnable() {


            @Override
            public void run() {
                try {
                    MusicPlayerActivity_.super.updateProgressBarViews(currentDuration, totalDuration, progress);
                } catch (RuntimeException e) {
                    Log.e("MusicPlayerActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void searchSongLyrics() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    MusicPlayerActivity_.super.searchSongLyrics();
                } catch (RuntimeException e) {
                    Log.e("MusicPlayerActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    @Override
    public void updateProgressBar() {
        BackgroundExecutor.execute(new Runnable() {


            @Override
            public void run() {
                try {
                    MusicPlayerActivity_.super.updateProgressBar();
                } catch (RuntimeException e) {
                    Log.e("MusicPlayerActivity_", "A runtime exception was thrown while executing code in a runnable", e);
                }
            }

        }
        );
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MusicPlayerActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MusicPlayerActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
