//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations.
//


package com.ventura.musicexplorer.ui.music;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.view.View.OnClickListener;
import android.view.ViewGroup.LayoutParams;
import android.widget.ImageButton;
import android.widget.SeekBar;
import android.widget.TextView;
import com.ventura.musicexplorer.R.id;
import com.ventura.musicexplorer.R.layout;

public final class MusicPlayerActivity_
    extends MusicPlayerActivity
{


    @Override
    public void onCreate(Bundle savedInstanceState) {
        init_(savedInstanceState);
        super.onCreate(savedInstanceState);
        setContentView(layout.musicplayer);
    }

    private void init_(Bundle savedInstanceState) {
    }

    private void afterSetContentView_() {
        btnPause = ((ImageButton) findViewById(id.btnPause));
        lblArtistName = ((TextView) findViewById(id.artist_name));
        lblSongTitle = ((TextView) findViewById(id.songTitle));
        btnNext = ((ImageButton) findViewById(id.btnNext));
        lblSongTotalDurationLabel = ((TextView) findViewById(id.songTotalDurationLabel));
        lblSongCurrentDuration = ((TextView) findViewById(id.songCurrentDurationLabel));
        btnPlay = ((ImageButton) findViewById(id.btnPlay));
        songProgressBar = ((SeekBar) findViewById(id.songProgressBar));
        btnPrevious = ((ImageButton) findViewById(id.btnPrevious));
        {
            View view = findViewById(id.btnNext);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.next();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnPause);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.pause();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnPrevious);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.prev();
                    }

                }
                );
            }
        }
        {
            View view = findViewById(id.btnPlay);
            if (view!= null) {
                view.setOnClickListener(new OnClickListener() {


                    @Override
                    public void onClick(View view) {
                        MusicPlayerActivity_.this.play();
                    }

                }
                );
            }
        }
        afterViews();
    }

    @Override
    public void setContentView(int layoutResID) {
        super.setContentView(layoutResID);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view, LayoutParams params) {
        super.setContentView(view, params);
        afterSetContentView_();
    }

    @Override
    public void setContentView(View view) {
        super.setContentView(view);
        afterSetContentView_();
    }

    public static MusicPlayerActivity_.IntentBuilder_ intent(Context context) {
        return new MusicPlayerActivity_.IntentBuilder_(context);
    }

    public static class IntentBuilder_ {

        private Context context_;
        private final Intent intent_;

        public IntentBuilder_(Context context) {
            context_ = context;
            intent_ = new Intent(context, MusicPlayerActivity_.class);
        }

        public Intent get() {
            return intent_;
        }

        public MusicPlayerActivity_.IntentBuilder_ flags(int flags) {
            intent_.setFlags(flags);
            return this;
        }

        public void start() {
            context_.startActivity(intent_);
        }

        public void startForResult(int requestCode) {
            if (context_ instanceof Activity) {
                ((Activity) context_).startActivityForResult(intent_, requestCode);
            } else {
                context_.startActivity(intent_);
            }
        }

    }

}
